services:
  django:
    build:
      context: ./myproject
      dockerfile: Dockerfile
    container_name: django_app
    env_file:
      - .env
    volumes:
      # - static_volume:/app/static
      - static_volume:/app/assets
      - media_volume:/app/media
    expose:
      - "8000"

    ports:
      - "8000:8000"

    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      # - static_volume:/app/static
      - static_volume:/app/assets
      - media_volume:/app/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  static_volume:
  media_volume:
  postgres_data:
